# Header
menu:
  Home: /
  About : /about
  Learn: /learn
  "Newsletter" : http://okcjs.us4.list-manage1.com/subscribe?u=a821c039e4e223f3947115270&id=694900f2a9
  Sponsors : /sponsors

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- recent_posts
- tag
- tagcloud
- archive

# Miscellaneous
google_analytics: UA-57887284-1
favicon: /favicon.png
twitter: okcjs
google_plus:
fb_admins:
fb_app_id:
